export const config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-tertiary-container": "#2c37a0",
                "on-tertiary-fixed-variant": "#2f3aa3",
                "surface-container-highest": "#2d3449",
                "secondary-fixed-dim": "#f9bd22",
                "tertiary-fixed-dim": "#bdc2ff",
                "inverse-on-surface": "#283044",
                "tertiary-container": "#a3abff",
                "outline": "#87929a",
                "surface-container-lowest": "#060e20",
                "error": "#ffb4ab",
                "primary-fixed": "#c4e7ff",
                "on-primary-fixed-variant": "#004c69",
                "inverse-surface": "#dae2fd",
                "surface-bright": "#31394d",
                "surface-container-high": "#222a3d",
                "on-tertiary": "#131e8c",
                "tertiary-fixed": "#e0e0ff",
                "outline-variant": "#3e484f",
                "on-secondary-container": "#5a4100",
                "secondary-fixed": "#ffdf9f",
                "secondary-container": "#e3aa00",
                "surface-variant": "#2d3449",
                "primary-container": "#38bdf8",
                "on-secondary-fixed": "#261a00",
                "on-background": "#dae2fd",
                "surface-container-low": "#131b2e",
                "primary-fixed-dim": "#7bd0ff",
                "on-primary": "#00354a",
                "on-primary-fixed": "#001e2c",
                "on-secondary": "#402d00",
                "secondary": "#ffc640",
                "tertiary": "#c5c9ff",
                "on-secondary-fixed-variant": "#5c4300",
                "surface-container": "#171f33",
                "on-surface": "#dae2fd",
                "surface-dim": "#0b1326",
                "error-container": "#93000a",
                "background": "#0b1326",
                "primary": "#8ed5ff",
                "on-surface-variant": "#bdc8d1",
                "surface-tint": "#7bd0ff",
                "on-error": "#690005",
                "on-primary-container": "#004965",
                "inverse-primary": "#00668a",
                "on-tertiary-fixed": "#000767",
                "on-error-container": "#ffdad6",
                "surface": "#0b1326"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "container-padding-desktop": "32px",
                "base": "8px",
                "stack-lg": "48px",
                "stack-sm": "12px",
                "stack-md": "24px",
                "gutter": "16px",
                "container-padding-mobile": "16px"
            },
            fontFamily: {
                "body-md": ["Be Vietnam Pro"],
                "display-lg": ["Plus Jakarta Sans"],
                "title-md": ["Plus Jakarta Sans"],
                "label-sm": ["Be Vietnam Pro"],
                "headline-lg": ["Plus Jakarta Sans"],
                "body-lg": ["Be Vietnam Pro"],
                "headline-lg-mobile": ["Plus Jakarta Sans"],
                "label-md": ["Be Vietnam Pro"]
            },
            fontSize: {
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
                "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
                "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
                "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
                "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }]
            }
        },
    }
};