import type { Player } from "@/types/adminPlayers";

export const MOCK_PLAYERS: Player[] = [
  {
    id: "1",
    username: "dragon_88",
    level: 15,
    experience: 7840,
    coins: 12500,
    completedMissions: 48,
    inProgressMissions: 2,
  },
  {
    id: "2",
    username: "lucky_star",
    level: 8,
    experience: 3200,
    coins: 5400,
    completedMissions: 18,
    inProgressMissions: 1,
  },
  {
    id: "3",
    username: "golden_fox",
    level: 22,
    experience: 15200,
    coins: 28500,
    completedMissions: 76,
    inProgressMissions: 3,
  },
  {
    id: "4",
    username: "night_hawk",
    level: 5,
    experience: 1500,
    coins: 2100,
    completedMissions: 8,
    inProgressMissions: 0,
  },
  {
    id: "5",
    username: "storm_rider",
    level: 12,
    experience: 6100,
    coins: 9800,
    completedMissions: 35,
    inProgressMissions: 2,
  },
  {
    id: "6",
    username: "crystal_queen",
    level: 19,
    experience: 11200,
    coins: 19200,
    completedMissions: 62,
    inProgressMissions: 1,
  },
  {
    id: "7",
    username: "phantom_ace",
    level: 3,
    experience: 700,
    coins: 900,
    completedMissions: 4,
    inProgressMissions: 2,
  },
  {
    id: "8",
    username: "velvet_wolf",
    level: 25,
    experience: 18900,
    coins: 34000,
    completedMissions: 91,
    inProgressMissions: 0,
  },
  {
    id: "9",
    username: "shadow_blade",
    level: 10,
    experience: 4500,
    coins: 7200,
    completedMissions: 24,
    inProgressMissions: 3,
  },
  {
    id: "10",
    username: "pixel_hero",
    level: 7,
    experience: 2600,
    coins: 3800,
    completedMissions: 14,
    inProgressMissions: 1,
  },
  {
    id: "11",
    username: "silver_arrow",
    level: 14,
    experience: 7100,
    coins: 11500,
    completedMissions: 42,
    inProgressMissions: 2,
  },
  {
    id: "12",
    username: "ember_phoenix",
    level: 20,
    experience: 13500,
    coins: 22100,
    completedMissions: 70,
    inProgressMissions: 1,
  },
  {
    id: "13",
    username: "cosmic_drift",
    level: 6,
    experience: 2000,
    coins: 2800,
    completedMissions: 10,
    inProgressMissions: 0,
  },
  {
    id: "14",
    username: "thunder_bolt",
    level: 16,
    experience: 8900,
    coins: 14900,
    completedMissions: 53,
    inProgressMissions: 3,
  },
  {
    id: "15",
    username: "sapphire_moon",
    level: 9,
    experience: 3800,
    coins: 6100,
    completedMissions: 20,
    inProgressMissions: 1,
  },
  {
    id: "16",
    username: "neon_tiger",
    level: 21,
    experience: 14200,
    coins: 25200,
    completedMissions: 73,
    inProgressMissions: 2,
  },
  {
    id: "17",
    username: "frost_byte",
    level: 4,
    experience: 1100,
    coins: 1500,
    completedMissions: 6,
    inProgressMissions: 1,
  },
  {
    id: "18",
    username: "inferno_king",
    level: 18,
    experience: 10300,
    coins: 17500,
    completedMissions: 58,
    inProgressMissions: 0,
  },
  {
    id: "19",
    username: "lunar_echo",
    level: 11,
    experience: 5300,
    coins: 8400,
    completedMissions: 29,
    inProgressMissions: 2,
  },
  {
    id: "20",
    username: "cyber_mage",
    level: 23,
    experience: 16800,
    coins: 31000,
    completedMissions: 84,
    inProgressMissions: 3,
  },
  {
    id: "21",
    username: "radiant_rook",
    level: 2,
    experience: 400,
    coins: 500,
    completedMissions: 2,
    inProgressMissions: 1,
  },
  {
    id: "22",
    username: "wild_vortex",
    level: 13,
    experience: 6600,
    coins: 10500,
    completedMissions: 38,
    inProgressMissions: 2,
  },
  {
    id: "23",
    username: "midnight_ace",
    level: 17,
    experience: 9600,
    coins: 16200,
    completedMissions: 55,
    inProgressMissions: 0,
  },
  {
    id: "24",
    username: "blaze_runner",
    level: 24,
    experience: 17800,
    coins: 32500,
    completedMissions: 88,
    inProgressMissions: 2,
  },
];
